### ISSUE TITLE
Support for 10.x?

### ISSUE THREAD

**Issue by Megachip** [LibreCodeCoop/trademark#1]
Planned?

**Comment by vitormattos** [comment]
Could you test and check if work fine?

**Comment by Megachip** [comment]
Menues loading, but got an crit error:

`[2022-09-09 18:12:34] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class 'PluginTrademarkToolbox' not found in ...plugins/trademark/front/internal.css.php at line 16  `

**Comment by cantinhodoce** [comment]
any estimate for releasing a compatible version for GLPI 10?

**Comment by pbsk8** [comment]
Any estimate for releasing a version compatible with GLPI 10?

**Comment by liviacarolgouvea** [comment]
> Any estimate for releasing a version compatible with GLPI 10?

Hi pbsk8,

This project is paused, so we don't have an update forecast.

But if you want, we can do this update for 200USD.

You can contribute through Patreon https://www.patreon.com/libresign

**Comment by rafaceazar** [comment]
hi there, I tried to enter the link of patreon, but does not open the link.

**Comment by liviacarolgouvea** [comment]
Hi @rafaceazar. 
You mean this one? https://www.patreon.com/libresign
Seems to work properly..
