### ISSUE TITLE
Logo interna - modo menu colapsado

### ISSUE THREAD

**Issue by jardeljsv** [LibreCodeCoop/trademark#3]
Prezados,
Poderiam corrigir essa questão que é quando usamos o menu lateral do glpi no modo colapsado a logo que é exibida é a do GLPI e nao a customizada.
![image](https://github.com/LibreCodeCoop/trademark/assets/72230557/73964fbf-3d4c-4f1e-ac80-4a740591590b)

![image](https://github.com/LibreCodeCoop/trademark/assets/72230557/3de8028c-adf0-4c41-b330-65b8560c7a1f)

Desde ja grato pelo plugin que é muito bom ajuda muito.

**Comment by vitormattos** [comment]
Olá @jardeljsv grato por relatar o ocorrido.
No momento não estou mantendo nenhum ambiente que esteja utilizando este plugin, então isto acaba reduzindo bastante a prioridade para realizar esta correção.
4 possíveis caminhos:

1. Aguardar alguém financiar que esta correção seja feita
2. Aguardar alguém da comunidade mandar um pull request com a correção
3. Investigar para encontrar a correção e mandar um pull request com a correção
4. Ajudar a financiar a correção

Vou marcar esta issue como `good first issue`
